### ISSUE TITLE
Inline styling for display of circle

### ISSUE THREAD

**Issue by flamencoflsh** [iqnivek/react-circular-progressbar#11]
@iqnivek , I think I am starting to get the gist of inline styling, but here is my current question... How do I differentiate between the styling for bar itself, path, trail, and text?

For example, I currently use:

const styles = {

 circularProgressLg: {
    paddingLeft: 40,
    paddingRight: 40,
    paddingBottom: 10,
    width: "50%",
    stroke: "#3e98c7",
    strokeLinecap: "round",
    transition: "stroke-dashoffset 0.5s ease 0s",
  }

};

And then use this to display:

         <div style={styles.circularProgressLg} className="col-lg-6 col-lg-offset-3 col-md-offset-3 col-md-6  col-sm-offset-2 col-sm-8 col-xs-12">
              <CircularProgressbar percentage={60.2} initialAnimation={true} />
            </div>

But how do I include the other properties for path, trail, and text?  

Also, I currently include "width" in the same set as the path properties instead of separately.  Is there a difference?

Thanks!

**Comment by flamencoflsh** [comment]
Hi @iqnivek !  

I'm still trying to figure out how I can change the attributes for the trail and text via inline styling. Using the code in the above post and this:

 <div style={styles.circularProgressLg} className="col-lg-6 col-lg-offset-3 col-md-offset-3 col-md-6  col-sm-offset-2 col-sm-8 col-xs-12">
              <CircularProgressbar percentage={60.2} initialAnimation={true} strokeWidth={5}/>
            </div>

... I am able to get the path to display.  But what is the syntax for modifying the text and trail to differentiate those properties from the ones for path?

Thanks!

**Comment by flamencoflsh** [comment]
Btw, @iqnivek , is it possible to differentiate between the stroke color of the circle and the fill of the text?  I tried putting them all in the same styling:


const styles = {

circularProgressLg: {
paddingLeft: 40,
paddingRight: 40,
paddingBottom: 10,
width: "50%",
stroke: "#3e98c7",
strokeLinecap: "round",
transition: "stroke-dashoffset 0.5s ease 0s",
fill: "#ff0000",
fontSize: "10px",
dominantBaseline: "middle",
textAnchor: "middle"
}

};

And it looks like the "stroke" color just took over for both.

Thx.

**Comment by flamencoflsh** [comment]
@tylerzika  Yes, I did.  But I haven't tried multiple circles with different styling yet. Let me know if it works.  

I am still trying to figure out how to make the text in the center have a different color from the path.  Have you figured that part out?

@iqnivek , please let us know if you have an answer =)

Thanks!

**Comment by flamencoflsh** [comment]
Update: I noticed that if I set strokeWidth to 0, then the fill color shows through.

**Comment by flamencoflsh** [comment]
@iqnivek What are the possible values for dominantBaseline?

**Comment by iqnivek** [comment]
@flamencoflsh I don't think you'll be able to customize the text/path/trail with inline styles - I'd just use regular CSS to do that. The [live demo page](http://www.kevinqi.com/react-circular-progressbar/) customizes all that stuff, and you can read the source for the demo [here](https://github.com/iqnivek/react-circular-progressbar/blob/master/docs/index.html) and [here](https://github.com/iqnivek/react-circular-progressbar/blob/master/docs/demo.jsx) which'll show you how to set it up. 

The CSS hooks available are:

```
.CircularProgressbar
.CircularProgressbar-trail
.CircularProgressbar-path
.CircularProgressbar-text
```

**Comment by iqnivek** [comment]
@tylerzika you can have multiple colors by having wrapper divs, and using CSS to customize the child classes. For instance:

```
# HTML
<div className="progressbar-red">
  <CircularProgressbar progress={80} />
</div>
<div className="progressbar-blue">
  <CircularProgressbar progress={80} />
</div>

# CSS
.red .CircularProgressbar-path {
  color: red;
}
.blue .CircularProgressbar-path {
  color: blue;
}
```

I should add an option to specify the className directly on the CircularProgressbar component, which would remove the need to have the wrapper div - I'll open an issue for it.
