### ISSUE TITLE
Failed prop type: Calling PropTypes validators directly is not supported

### ISSUE THREAD

**Issue by maxrosecollins** [iqnivek/react-circular-progressbar#19]
When using

`<CircularProgressbar percentage={domain.attributes.overview.top_three} strokeWidth={16} />`

I am getting the following warning
`warning.js:36 Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them.`

**Comment by maxrosecollins** [comment]
Ah this is a duplicate of issue #18

**Comment by iqnivek** [comment]
yup, but thanks for reporting! will close this one.
