### ISSUE TITLE
Feature request: way to render without <text>

### ISSUE THREAD

**Issue by jedwards1211** [iqnivek/react-circular-progressbar#24]
I could hide the text by rendering with `textForPercentage={() => ''}`, but it would be cleaner if I could prevent it from rendering any `<text>` at all.

It could avoid rendering `<text>` if `textForPercentage={null}` or if it returns something falsy.

Personally I think having a `textForPercentage` function is more complicated than necessary; since one is always passing in the `percentage`, one could easily just pass in ``text={`${percentage}%`}`` as well if this lib supported it.  Same goes for `classForProperty`.

Note: `react-bootstrap` progress bars, which don't show any text by default, can be passed text to display as `children`.

**Comment by iqnivek** [comment]
really sorry this was hanging around for so long! just merged your PR and published it in v0.4.1.

I didn't think about it much until you raised it, but I totally agree with your feedback that classForPercentage and textForPercentage are unnecessarily complicated - I'd simply overthought things when coming up with the initial props. I'll create a new issue to add a `text` prop and deprecate those other two props.
