### ISSUE TITLE
Not working showing just simple text

### ISSUE THREAD

**Issue by PradeepJaiswar** [iqnivek/react-circular-progressbar#27]
Just rendering simple text

```
import React from 'react';

import CircularProgressbar from 'react-circular-progressbar';

class ProgressChart extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      progress: 60,
    };
  }
  render() {
    return (
      <CircularProgressbar percentage={this.state.progress} />
    );
  }
}

export default ProgressChart;
```

Included style in index.html

`<link rel="stylesheet" type="text/css" href="https://raw.githubusercontent.com/iqnivek/react-circular-progressbar/master/src/styles.css">`

what am I doing wrong?

<img width="1227" alt="screen shot 2017-09-21 at 12 39 26 pm" src="https://user-images.githubusercontent.com/4545996/30683176-f98cdc8c-9ec9-11e7-8f66-302d5dd1c7de.png">

**Comment by andreysaleba** [comment]
I believe this is related to this console warn message: "Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://raw.githubusercontent.com/iqnivek/react-circular-progressbar/master/docs/styles.css"."
If you include it, like the description states: 
"Important: you'll also need to copy src/styles.css into your repo to use the default styling!"
it will work properly

**Comment by PradeepJaiswar** [comment]
oh! How can I miss it 😬 

Thanks, this should work fine.

**Comment by iqnivek** [comment]
thanks for diagnosing @andreysaleba! 👏
