### ISSUE TITLE
Bug: Stroke width defines starting and ending position

### ISSUE THREAD

**Issue by anault** [iqnivek/react-circular-progressbar#28]
This progress bar is at 50%

Stroke width of 4:
![r4](https://user-images.githubusercontent.com/6646230/30815196-6c9dde2e-a1e0-11e7-908e-2d68d719648d.png)

Stroke width of 16:
![r3](https://user-images.githubusercontent.com/6646230/30815187-66bc10de-a1e0-11e7-8e31-3ac9a3374208.png)

Notice how at width 16 the stroke goes beyond the 50% mark (center of house) (kind of like a horseshoe). I'm guessing it's 16px beyond the center 😛 .

**Comment by anault** [comment]
Nvm, I was using `stroke-linecap: square;` while I should have used `stroke-linecap: butt;`

**Comment by iqnivek** [comment]
glad you figured it out!

**Comment by AlFalahTaieb** [comment]
How do you add an icon into the progress bar ?
