### ISSUE TITLE
How to do a  Circular progress bar around an image ?

### ISSUE THREAD

**Issue by AlFalahTaieb** [iqnivek/react-circular-progressbar#32]
How would I go about drawing the circle around the image?

**Comment by iqnivek** [comment]
Not sure how other folks have done it, but you can do it with absolute positioning with CSS, e.g.:

```
<div style={{position: 'relative', width: '100px', height: '100px'}}>
  <img style={{position: 'absolute', width: '100%', top: '10px'}} src="http://barkpost-assets.s3.amazonaws.com/wp-content/uploads/2013/11/3dDoge.gif" />
  <div style={{position: 'absolute'}}>
    <CircularProgressbar
      percentage={20}
      textForPercentage={null}
    />
  </div>
</div>
```

Result:

<img width="131" alt="screen shot 2017-10-14 at 12 34 24 pm" src="https://user-images.githubusercontent.com/396006/31578742-55a03900-b0dc-11e7-9cd0-2abedb0c9f0c.png">

**Comment by AlFalahTaieb** [comment]
Love the exemple !! Thank you sir

**Comment by sjorsvanheuveln** [comment]
Is there a way to manage the image overflowing the circle?

**Comment by sjorsvanheuveln** [comment]
Found the CSS solution. Maybe nice for you to add it to the example as it would make the implementation for images easier.

Add this attribute to the styling object: 
`borderRadius: '50%'`

**Comment by iqnivek** [comment]
@sjorsvanheuveln yup, if you're putting in an image that covers the full width/height of the progressbar, then `borderRadius: '50%'` is a good idea.

**Comment by iqnivek** [comment]
I created a CodeSandbox that demonstrates creating a wrapper `CustomContentProgressbar` that users flexbox + absolute positioning so you can put arbitrary children (e.g. divs, img, etc) as children of `CustomContentProgressbar` and have the children be centered with flexbox.

Just adding this example because flexbox centering is better than the hardcoded pixel centering I did in my earlier example, and the wrapper component pattern is more reusable.

CodeSandbox: https://codesandbox.io/s/qlr7w0rm29

<img width="500" alt="screen shot 2018-02-27 at 9 44 53 pm" src="https://user-images.githubusercontent.com/396006/36771848-bb36872e-1c07-11e8-9b80-5e58221b14d7.png">

**Comment by mar753** [comment]
> I created a CodeSandbox that demonstrates creating a wrapper `CustomContentProgressbar` that users flexbox + absolute positioning so you can put arbitrary children (e.g. divs, img, etc) as children of `CustomContentProgressbar` and have the children be centered with flexbox.
> 
> Just adding this example because flexbox centering is better than the hardcoded pixel centering I did in my earlier example, and the wrapper component pattern is more reusable.
> 
> CodeSandbox: https://codesandbox.io/s/qlr7w0rm29
> 
> <img alt="screen shot 2018-02-27 at 9 44 53 pm" width="500" src="https://user-images.githubusercontent.com/396006/36771848-bb36872e-1c07-11e8-9b80-5e58221b14d7.png">

CodeSandbox is currently not compatible with IE11 (StackBlitz seems to work on IE11: https://stackblitz.com/edit/react), but this solution will not work properly with IE11. To make it work you need to add weight/height to the div which wraps CircularProgressbar component as well:
 ```
<div style={{ position: "absolute", width: "100%", height: "100%"  }}>
  <CircularProgressbar {...otherProps} />
</div>
```

**Comment by mar753** [comment]
> I created a CodeSandbox that demonstrates creating a wrapper `CustomContentProgressbar` that users flexbox + absolute positioning so you can put arbitrary children (e.g. divs, img, etc) as children of `CustomContentProgressbar` and have the children be centered with flexbox.
> 
> Just adding this example because flexbox centering is better than the hardcoded pixel centering I did in my earlier example, and the wrapper component pattern is more reusable.
> 
> CodeSandbox: https://codesandbox.io/s/qlr7w0rm29
> 
> <img alt="screen shot 2018-02-27 at 9 44 53 pm" width="500" src="https://user-images.githubusercontent.com/396006/36771848-bb36872e-1c07-11e8-9b80-5e58221b14d7.png">

CodeSandbox is currently not compatible with IE11 (StackBlitz seems to work on IE11: https://stackblitz.com/edit/react), but this solution will not work properly with IE11. To make it work you need to add width/height to the div which wraps CircularProgressbar component as well:
 ```
<div style={{ position: "absolute", width: "100%", height: "100%"  }}>
  <CircularProgressbar {...otherProps} />
</div>
```
