### ISSUE TITLE
Add documentation for the properties that the component accepts

### ISSUE THREAD

**Issue by carloscuatin** [iqnivek/react-circular-progressbar#4]

**Comment by iqnivek** [comment]
That's what the "Props" section on the live demo page is meant to be: http://www.kevinqi.com/react-circular-progressbar. This is mentioned in the README, but do you think it's hard to find or that people would expect that documentation to be in the README itself?

**Comment by carloscuatin** [comment]
I would expect in the readme something where tell me the name of the property type, default value and a brief description

**Comment by iqnivek** [comment]
Okay, you're probably right that it's better in the README rather than the live demo page. I'll try to move the prop docs there at some point. Thanks!

**Comment by bryantee** [comment]
Agreed, in the readme was where I expected to find it.
