### ISSUE TITLE
Include styles.css in built module

### ISSUE THREAD

**Issue by marchaos** [iqnivek/react-circular-progressbar#40]
Hey, 

It would be nice if the styles were included in the built module so that they could be included from node modules.

**Comment by iqnivek** [comment]
yeah, that sounds like a good idea. I'm not sure what the best setup is for that yet, so suggestions/PRs are welcome, but I'll take a look into it too.

**Comment by var-bp** [comment]
Hi, please move styles.css to build folder.

**Comment by iqnivek** [comment]
Sorry for the delay on this - I've added styles to `dist/styles.css` in v0.8.0. If you have a CSS loader you can now do:

```
import CircularProgressbar from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";
```

You can see a working example here: https://codesandbox.io/s/vymm4oln6y

Thanks for the suggestion @marchaos!
