### ISSUE TITLE
Line breaks and custom formatting in Circular progressbar text

### ISSUE THREAD

**Issue by boriskogan81** [iqnivek/react-circular-progressbar#44]
If I want to custom-format this text, for instance, by breaking it up into several lines of different font sizes, or inserting several <span> elements, is this possible? Should it be a pr?

**Comment by iqnivek** [comment]
Yeah, this could technically be implemented in svg with a `text` prop that can be passed a render function. However, building custom text with svg internals wouldn't be super convenient to work with.

I think a more practical solution is to be able to pass arbitrary children to the component that overlaid and centered, which can be used in lieu of SVG text.

For the time being, I've created an example wrapper component that can do that here: https://codesandbox.io/s/mzr5k37o6p

<img width="400" alt="screen shot 2018-02-08 at 9 30 27 pm" src="https://user-images.githubusercontent.com/396006/36013148-64baa96a-0d17-11e8-834d-c8dfe0335754.png">

**Comment by boriskogan81** [comment]
That's perfect. 

I agree that text should be done as text, not SVG, as much as possible.

Thanks a ton.
