### ISSUE TITLE
How to make the progress bar animate like a pie chart instead of it filling up the border?

### ISSUE THREAD

**Issue by Praneetha-CK** [iqnivek/react-circular-progressbar#50]
![pie chart](https://user-images.githubusercontent.com/19527348/38161932-b0b63bda-34f5-11e8-8085-1e67cc84a0f7.PNG)

Is there any way that I can make the progress bar looks like this?

**Comment by iqnivek** [comment]
yup, I think you can achieve it with the combination of [this technique](https://github.com/iqnivek/react-circular-progressbar/issues/44), which allows you to overlay text on top of the progressbar, and [modifying strokeWidth and styles](https://github.com/iqnivek/react-circular-progressbar/issues/47) to make it look like a pie chart.

I don't have time at the moment, but I can create a codesandbox demo later. In the meantime, you can see if you can combine those to get what you want.

**Comment by iqnivek** [comment]
Here's a demo showing how it's done: https://codesandbox.io/s/qxz12ym92w

<img width="500" alt="screen shot 2018-04-02 at 9 08 41 pm" src="https://user-images.githubusercontent.com/396006/38228754-10bad520-36ba-11e8-834d-f7af22f97fe8.png">

Going to close this, but feel free to ask if you've got followup questions!
