### ISSUE TITLE
Radius

### ISSUE THREAD

**Issue by ommyan** [iqnivek/react-circular-progressbar#51]
nice component , great work.

anyway , how to change radius circular progress, expected to simply change radius

`<CircularProgressbar percentage={this.state.value1} radius={25} />`

thanks

**Comment by iqnivek** [comment]
You can size the component simply by specifying the size of the wrapping container, e.g.:

```
<div style={{ width: '100px' }}>
  <CircularProgressbar percentage={20} />
</div>
```

If you want to change the size of the bar itself, you can use the `strokeWidth` prop:

```
<div style={{ width: '100px' }}>
  <CircularProgressbar percentage={20} strokeWidth={15} />
</div>
```

Hope that answers your question!
