### ISSUE TITLE
Progres not based on the percentage

### ISSUE THREAD

**Issue by piotrooo** [iqnivek/react-circular-progressbar#52]
Hey,

firstly thanks for good plugin and nice work!

I have some idea which you can try to consider is ok.
In you plugin you base on the percentage and max value expressed by the 100%. For stuff which is based on the percent is ok. But I faced with following problem, I needed to run a circular progress based on the n-seconds, that's mean I need to countdown (increments/decrements). Max value is 5 and need to countdown to 0 (increments should be possible too, passed as an option).

I don't know is that idea will be good for you, but changes shouldn't be hard I guess.

**Comment by iqnivek** [comment]
If I'm understanding you correctly, this is what you're looking for? https://codesandbox.io/s/23w8j4mk30

It's a little awkward, but we don't strictly need to add new functionality to achieve this - can simply convert from seconds to percentages instead and write wrapper components like `ChangingProgressbar` and `CountdownProgressbar` to abstract out the details.

Going to close this, but let me know if this doesn't address your need. Thanks!

**Comment by piotrooo** [comment]
Thanks, nice approach I didn't think like this.

PS. I want to archive this: https://codesandbox.io/s/p7621n2zlj but is a small change in the `_.rand` function.

**Comment by kevinsqi** [comment]
FYI - this is now much easier to manage in v2.0.0 with `props.minValue` and `props.maxValue`. Can just set maxValue=5.
