### ISSUE TITLE
`styles.root` is not applied

### ISSUE THREAD

**Issue by kenzierocks** [iqnivek/react-circular-progressbar#55]
The code states that there is a property for applying CSS styling to the root node, but it's unused in the actual rendering. Could this be fixed?

**Comment by iqnivek** [comment]
Just to be clear, you mean `<CircularProgressbar styles={{ root: { ...some styles... } }} />` isn't working, right? If so, then yeah - I'm seeing that that's not being set correctly and I can fix shortly.
