### ISSUE TITLE
Remove 'Unwind' Animation

### ISSUE THREAD

**Issue by KayBeSee** [iqnivek/react-circular-progressbar#56]
I am using this component to make a timer component and was wondering how I could go about removing the 'unwind' animation after I reset the percentage to 0.

Right now, once the timer runs out the progressbar follows back around the circle the way it came. I want to have the progressbar just remove it's progress and start how it began. Any ideas?

**Comment by iqnivek** [comment]
hmm, that's an interesting question! I don't have an answer off the top of my head but I can investigate. Open to ideas here - for reference, [this CSS declaration](https://github.com/iqnivek/react-circular-progressbar/blob/master/src/styles.css#L20) is what's responsible for the default animation behavior.

**Comment by KayBeSee** [comment]
I was able to solve this by adding the following styles to the component:

styles={{
   path: {
   transition: 'none',
   animation: 'stroke-dashoffset 0.5s ease 0s',
   stroke: this.props.color
}
```

I am using this for a timer that ticks every second. The only problem with my solution is that it doesn't smoothly transition between each tick as it does with the transition. If you find a way to make it more smooth, please let me know!

**Comment by iqnivek** [comment]
Think I got it to work! See https://codesandbox.io/s/6295zr7jrn

The key is to set `transition: 'none'` only when the percentage is 0, like so:

```jsx
<CircularProgressbar
  percentage={...}
  styles={
    path: {
      transition: currentPercentage === 0 ? 'none' : 'stroke-dashoffset 0.5s ease 0s',
    }
  }
/>
```

This causes the transition from 100% to 0% to not happen.

**Comment by KayBeSee** [comment]
That's perfect. Thank you!
