### ISSUE TITLE
Can we create segmented progressbars?

### ISSUE THREAD

**Issue by koolkarni** [iqnivek/react-circular-progressbar#57]
![screen shot 2018-06-18 at 5 54 45 pm](https://user-images.githubusercontent.com/16875126/41617294-f50753ca-73b4-11e8-98fc-5da233648ab5.png)

**Comment by iqnivek** [comment]
Managed to do it by overlaying divs on top of the CircularProgressbar using absolute positioning. It's a little involved, but seems to look reasonable!

Check it out: https://codesandbox.io/s/ov22pywr19

<img width="500" alt="screen shot 2018-06-20 at 10 42 46 pm" src="https://user-images.githubusercontent.com/396006/41700088-b89810e6-74db-11e8-8a60-fb7fb1db5f15.png">
