### ISSUE TITLE
Make the component resizable

### ISSUE THREAD

**Issue by vic-topcoder** [iqnivek/react-circular-progressbar#62]
Right now the component is scaled down to fit the container, but the viewbox is always 100x100px. During scaling down the interface is rendered with approximation and the progress bar is not sharp as a full resolution render. It would be very useful to actually pass the size as parameter and calculate based on that.

**Comment by iqnivek** [comment]
It would help a bunch if you could you show me an example of the lack of sharpness. I have a [codesandbox here](https://codesandbox.io/s/8y0p5x0k98) and changing the size of the window to various widths seems to keep the progress bar reasonably sharp - do you think you could fork that example and set up a specific case where you're seeing blurriness? Attaching a screenshot of what you're seeing would also be helpful. Thanks!

**Comment by iqnivek** [comment]
Closing this for now, but I'd be happy to revisit if you're able to provide an example case.

**Comment by gca-bliss** [comment]
Hi, reopening this as I ran into this with minimal progress components.

![image](https://user-images.githubusercontent.com/63356450/82515439-232aa200-9b10-11ea-8790-46e8413440ff.png)

The above example is 64 x 64. It's a bit ragged, specially noticeable on animations
