### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by RodruF** [iqnivek/react-circular-progressbar#63]
Why the example of CodeSandBox don't move or isn't animated?

**Comment by iqnivek** [comment]
I simply didn't add an animated example to that sandbox yet. Animation requires the percentage to change, or to have the `initialAnimation` prop set to true, which the main codesandbox doesn't use. I'll add that later, but in the meantime [this codesandbox](https://codesandbox.io/s/2zrwknnvwj) does show how animation looks.
