### ISSUE TITLE
Feature request: initialAnimation speed/delay

### ISSUE THREAD

**Issue by Wgil** [iqnivek/react-circular-progressbar#64]
Hello!

I would like to run the `initialAnimation` when my component is already mounted and also I would like to change the animation speed. Is that currently possible? I could do a pull request if you are interested in this. :-)

Thank you.

**Comment by iqnivek** [comment]
Animation speed is already configurable with CSS/styles: https://github.com/iqnivek/react-circular-progressbar/issues/54

You can run the animation whenever you want simply by changing the `percentage` prop value from 0 to the desired percentage. See https://codesandbox.io/s/81wzmm8n00 for an example of that.

Let me know if this doesn't address what you need.

**Comment by Wgil** [comment]
Hello @iqnivek :-)

That certainly solves the scenario I'm facing since some of my progress bars are going to be loaded asynchronously. However, I think that I also will need to run the animation when the user scrolls down and the bars appear for the first time on the screen. I'm not pretty sure if this would be page responsibility or circles bars itself. Let me hear your thoughts on this, please.

Thank you!

**Comment by iqnivek** [comment]
This should definitely be the page's responsibility. Fortunately what you're asking for is quite doable - I looked into it and react-visibility-sensor will do the trick for detecting and animating when the progressbar becomes visible.

I've updated the codesandbox to show how that would work: https://codesandbox.io/s/81wzmm8n00

Hope this helps!

**Comment by Wgil** [comment]
@iqnivek Thank you very much! You're so kind.
