### ISSUE TITLE
How to delay in the circular animation?

### ISSUE THREAD

**Issue by Taimoormk** [iqnivek/react-circular-progressbar#65]
Hello, great repo thank you for the nice work.

One query, how we could add a little delay in circular animation on the component load?

**Comment by iqnivek** [comment]
Hi @Taimoormk! 

If you just want a fixed delay, you could wrap the progressbar in another component which has a `setTimeout` call in `componentDidMount` which sets the `percentage` prop from 0 to the desired percentage after a timeout, which would achieve what you want.

If you want to delay the animation until the component is visible, see this thread: https://github.com/iqnivek/react-circular-progressbar/issues/64. It has an example codesandbox which implements the visibility detection: https://codesandbox.io/s/81wzmm8n00

Does this address your question?

**Comment by Taimoormk** [comment]
It sure does, thank you for a detailed explanation and the sample code.

Cheers
