### ISSUE TITLE
View config not found for name path.Make sure to start component names with a capital letter.

### ISSUE THREAD

**Issue by dailydoc7755** [iqnivek/react-circular-progressbar#66]
![img_73d153789def-1](https://user-images.githubusercontent.com/38548609/47216445-9616e880-d3c2-11e8-8d91-8485472fdbb3.jpeg)

**Comment by iqnivek** [comment]
This is a DOM-based component and doesn't work in react native. I believe there should be alternatives built for react native if you search for e.g. "react native circular progress", though.
