### ISSUE TITLE
Is it possible to bind "percentage" to a timer component?

### ISSUE THREAD

**Issue by closfx** [iqnivek/react-circular-progressbar#67]
Hello, I'm attempting to dynamically bind the "percentage" value to a timer component. I am able to get the progress circle percentage to update with a certain function, but I am unable to include that function  in  ComponentDidUpdate()...it causes an infinite loop. So, right now, the progress circle updates whenever my function is called, but I am unable to animate the percentage dynamically. Any suggestions?

Thanks,
Carlos

**Comment by iqnivek** [comment]
Hi @closfx! You should be able to update the percentage prop without causing an infinite loop - and you don't necessarily need to update that in a componentDidUpdate call. Here's an example of changing the percentage prop with setTimeout: https://codesandbox.io/s/x29rxrr4kw

If you're still having issues, please create a codesandbox demonstrating the issue and I can take a look.
