### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by gagan0723** [iqnivek/react-circular-progressbar#69]
Thanks, @iqnivek and **the community** for the awesome work.
I was trying have something similar to below-attached gif, but could not get it working.

![pie-progress](https://user-images.githubusercontent.com/6944095/47970200-a4335d00-e082-11e8-98ad-6206659c4443.gif)

What I am trying to achieve is a **blog reading pie-progress**, that shows what percentage the user has scrolled through the article.

Thanks 🙏

**Comment by iqnivek** [comment]
Thanks for the kind words @gagan0723! 

Can you show a codesandbox example of what you currently have? You should be able to achieve this by setting the `percentage` prop whenever the scroll level changes.

**Comment by gagan0723** [comment]
@iqnivek [here](https://codesandbox.io/s/nnqpj643ym) the link.
I have some comments, please read them.
Thanks 😊

**Comment by iqnivek** [comment]
I think I got it?

<img width="137" alt="screen shot 2018-11-07 at 11 11 03 pm" src="https://user-images.githubusercontent.com/396006/48183090-70ef0900-e2e2-11e8-8ae7-c519954d2219.png">

See: https://codesandbox.io/s/vop51mwx7

**Comment by gagan0723** [comment]
Thanks for helping me out.

Is there a way to make paths a bit smaller in size?

**Comment by iqnivek** [comment]
Use the strokeWidth prop? All the dimensions should be configurable one way or another. Good luck!

**Comment by gagan0723** [comment]
Thanks.
