### ISSUE TITLE
Not working. It is just showing the value with percent

### ISSUE THREAD

**Issue by skalekarr** [iqnivek/react-circular-progressbar#7]
It is not showing the circle and the progress.
I have added width too to the container. It is just showing the value with `%` symbol

**Comment by maticaputti** [comment]
> Include the default styles into your CSS by copying src/styles.css into your repo.

**Comment by iqnivek** [comment]
^ yeah, that's the most likely culprit - make sure you've copied [this stylesheet](https://raw.githubusercontent.com/iqnivek/react-circular-progressbar/master/src/styles.css) to your repo and include it in your CSS package.
