### ISSUE TITLE
In MS edge,IE11 and FireFox The text is not in middle.

### ISSUE THREAD

**Issue by JimZhang1028** [iqnivek/react-circular-progressbar#70]
In MS edge,IE11 and FireFox, CSS dominant-baseline is not work.
and in your source for the text we can not add dy.

**Comment by iqnivek** [comment]
Yup, this is a known issue (#35). I'm not planning to create a browser-specific workaround, unless there's a very simple fix that I'm missing.

You can still achieve vertically centered text in IE though - I'd recommend using the approach of overlaying centered content on top of the progressbar as described here: https://github.com/iqnivek/react-circular-progressbar/issues/32#issuecomment-369129732
