### ISSUE TITLE
How to add shadow or a hollow outline to circular progressbar?

### ISSUE THREAD

**Issue by bhumi0901** [iqnivek/react-circular-progressbar#72]
Hello,
I have used react-circular-progressbar in my react project. I want to add a hollow outline around the progressbar as shown in the image below:

![image](https://user-images.githubusercontent.com/44312246/51513216-bc1faf00-1e2f-11e9-879e-3ccd22c02d9e.png)

Is there any way to get this kind of progreaabar using this package?

**Comment by andy3wood** [comment]
Hey I achieved something similar maybe this will help you:
![screen shot 2019-01-25 at 15 33 08](https://user-images.githubusercontent.com/20561665/51755527-cf907b80-20b6-11e9-9966-f8bb4ec97042.png)
`styles={{`
          `background: {
            fill: 'white',
            transform: 'scale(0.8)',
            transformOrigin: 'center center',
          },`
`root: {
            width: size,
            height: size,
            filter: 'drop-shadow(10px 10px 20px lightgray)',
          },`
`trail: {
            strokeWidth: 0,
          },`
`text: {
            fill: color,
            fontSize: 22,
            fontWeight: 800,
            animation: 'fadein 2s',
          },`
`}}`

**Comment by iqnivek** [comment]
@bhumi0901 I don't know if there's a great way to do exactly what you're asking for with straight CSS without any source modifications - there doesn't appear to be a simple solution to add a border directly to an SVG path (though I could be wrong on this). Adding this functionality to the lib seems pretty niche and is likely out of scope, unfortunately.

I realize that's not super ideal, you could achieve what you want by creating a wrapper that stacks two progressbars on top of each other using e.g. [CustomContentProgressbar](https://codesandbox.io/s/qlr7w0rm29), and have the bottom one be wider but have reduced opacity. Hope this helps.
