### ISSUE TITLE
Display circle

### ISSUE THREAD

**Issue by flamencoflsh** [iqnivek/react-circular-progressbar#9]
Hi @iqnivek !

I tried using this component in this manner:

 <div style={styles.circularProgressLg} className="col-lg-6 col-lg-offset-3 col-md-offset-3 col-md-6  col-sm-offset-2 col-sm-8 col-xs-12">
              <CircularProgressbar percentage={60.2} initialAnimation={true} strokeWidth={5}/>
            </div>
            <div style={styles.circularProgressSm} className="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <CircularProgressbar percentage={30.8} initialAnimation={true} />
            </div>
            <div style={styles.circularProgressSm} className="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <CircularProgressbar percentage={24.2} initialAnimation={true} />
            </div>
            <div style={styles.circularProgressSm} className="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <CircularProgressbar percentage={72.8} initialAnimation={true} />
            </div>

However, currently when I run it, only the percentage (eg. 60.2%) is displayed, but not the circle itself.  What am I doing wrong..?

**Comment by iqnivek** [comment]
You may not have copied the default CSS over, which styles the progressbar. Take a look here: https://github.com/iqnivek/react-circular-progressbar/issues/7. Let me know if that doesn't fix the issue - thanks!

**Comment by flamencoflsh** [comment]
@iqnivek, would it be possible to create these settings directly in my current file?  If so, what would be the syntax? Thx.

**Comment by iqnivek** [comment]
You could either re-implement the CSS using inline styles (search for "react inline styles"), or import the CSS into your component using e.g. css-loader. Or you could just add the styles to your existing CSS.

**Comment by flamencoflsh** [comment]
@iqnivek, I copied them into my current style.css file, but it doesn't seem to make a difference.  So just wondering if I can add them directly into the current file. 

With inline styles, would it look like this?

const CircularProgressbar {
  width: 100%;
};

const ircularProgressbar-path {
  stroke: #3e98c7;
  stroke-linecap: round;
  transition: stroke-dashoffset 0.5s ease 0s;
}

const CircularProgressbar-trail {
  stroke: #d6d6d6;
}

const CircularProgressbar-text {
  fill: #3e98c7;
  font-size: 20px;
  dominant-baseline: middle;
  text-anchor: middle;
}

And would I need to add anything this code?

  <div style={styles.circularProgressLg} className="col-lg-6 col-lg-offset-3 col-md-offset-3 col-md-6  col-sm-offset-2 col-sm-8 col-xs-12">
              <CircularProgressbar percentage={60.2} initialAnimation={true} strokeWidth={5}/>
            </div>
            <div style={styles.circularProgressSm} className="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <CircularProgressbar percentage={30.8} initialAnimation={true} />
            </div>
            <div style={styles.circularProgressSm} className="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <CircularProgressbar percentage={24.2} initialAnimation={true} />
            </div>
            <div style={styles.circularProgressSm} className="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <CircularProgressbar percentage={72.8} initialAnimation={true} />
            </div>

Thanks!

**Comment by flamencoflsh** [comment]
<div style={styles.circularProgressLg} className="col-lg-6 col-lg-offset-3 col-md-offset-3 col-md-6  col-sm-offset-2 col-sm-8 col-xs-12">
              <CircularProgressbar percentage={60.2} initialAnimation={true} strokeWidth={5}/>
            </div>
            <div style={styles.circularProgressSm} className="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <CircularProgressbar percentage={30.8} initialAnimation={true} />
            </div>
            <div style={styles.circularProgressSm} className="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <CircularProgressbar percentage={24.2} initialAnimation={true} />
            </div>
            <div style={styles.circularProgressSm} className="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <CircularProgressbar percentage={72.8} initialAnimation={true} />
            </div>
